connected login form to API endpoint
rzheng95/e-commerce-platform pull request #5
Opened 2023-10-10 03:09 UTC by Huayao-Zheng

connected login form to API endpoint

2023-10-10 23:17 UTC, qq1055394882 approved these changes
reviewed and provided a feedback in discord.

2023-10-11 04:10 UTC, rzheng95 requested changes

2023-10-11 04:10 UTC, rzheng95 commented on e-commerce-ui/src/app/login/login.component.ts
> +      )
Move the login components into a `auth` folder. Create an authentication service (ex,. `auth.service.ts`) and put all authentication-related HTTP requests in the service file. You can generate the service files using ng command `ng g s auth/auth`

2023-10-11 04:10 UTC, rzheng95 commented on e-commerce-ui/src/app/login/login.component.ts
>      });
Inject FormBuilder and instantiate the `emailForm` with FormBuilder

2023-10-12 13:23 UTC, rzheng95 requested changes

2023-10-12 13:23 UTC, rzheng95 commented on e-commerce-ui/src/app/auth/auth.service.ts
> +  onLogin(email: string) {
Specify the return type.

2023-10-12 13:23 UTC, rzheng95 commented on e-commerce-ui/src/app/auth/auth.service.ts
> +      );
Do not subscribe in service files. Only subscribe in components files.

2023-10-12 13:23 UTC, rzheng95 commented on e-commerce-ui/src/app/auth/login/login.component.html
> +    >
Fix the formatting

2023-10-13 02:39 UTC, rzheng95 approved these changes

2023-10-13 02:39 UTC, merged